// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCR_oI854tKhaDucdsdYG04JfWad_oJs',
    appId: '1:860450586024:web:c8d5b8da4f0a5bc5f9b19d',
    messagingSenderId: '860450586024',
    projectId: 'flutter-cse-464-group-11',
    authDomain: 'flutter-cse-464-group-11.firebaseapp.com',
    storageBucket: 'flutter-cse-464-group-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4AalLUkBXy39GzYOtPaRyndow7Q0Euz0',
    appId: '1:860450586024:android:cee5ade2e918d050f9b19d',
    messagingSenderId: '860450586024',
    projectId: 'flutter-cse-464-group-11',
    storageBucket: 'flutter-cse-464-group-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZuWl8GiAmbGzdOYZoSx77pgOcp3-VF8',
    appId: '1:860450586024:ios:7e0bb6ba05e71a93f9b19d',
    messagingSenderId: '860450586024',
    projectId: 'flutter-cse-464-group-11',
    storageBucket: 'flutter-cse-464-group-11.firebasestorage.app',
    iosBundleId: 'com.example.aiLanguageTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCR_oI854tKhaDucdsdYG04JfWad_oJs',
    appId: '1:860450586024:web:fbbaafa20ab5f3c7f9b19d',
    messagingSenderId: '860450586024',
    projectId: 'flutter-cse-464-group-11',
    authDomain: 'flutter-cse-464-group-11.firebaseapp.com',
    storageBucket: 'flutter-cse-464-group-11.firebasestorage.app',
  );
}
